- name: Update repository cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install proxmoxer
  ansible.builtin.apt:
    name: python3-proxmoxer
    state: latest
