- name: Install sudo package
  ansible.builtin.apt:
    name: sudo
    update_cache: false

- name: Create user {{ pvenode.user }}
  ansible.builtin.user:
    name: "{{ pvenode.user }}"
    shell: '/bin/bash'

- name: Add Ansible ssh key
  ansible.builtin.authorized_key:
    user: "{{ pvenode.user }}"
    key: "{{ lookup('file', '/home/{{ pvenode.user }}/.ssh/id_rsa.pub') }}" 

- name: Add {{ pvenode.user }} to sudo
  ansible.builtin.user:
    name: "{{ pvenode.user }}"
    groups: sudo
    append: true
    state: present
    createhome: true

- name: Make sudo without password for {{ pvenode.user }}
  ansible.builtin.copy:
    dest: /etc/sudoers.d/80-ansible-sudo-user
    content: "{{ pvenode.user }} ALL=(ALL) NOPASSWD:ALL"
    mode: 0440
